In [7]:
from utils.data_loader import *

In [8]:
x = np.arange(100)
batch_size = 10
seq_length = 3
num_batch = int(len(x) / (batch_size * seq_length))

# 딱 나누어 떨어지지 않는 경우, 남겨지는 부분을 버림.
# https://github.com/sherjilozair/char-rnn-tensorflow/blob/master/utils.py 의 이해를 위하여 작성해본 코드.
x = x[:num_batch * batch_size * seq_length]
x_batches = np.split(x.reshape(batch_size, -1), num_batch, 1)
print(x_batches[0])
print(x_batches[1])

[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]
 [27 28 29]
 [36 37 38]
 [45 46 47]
 [54 55 56]
 [63 64 65]
 [72 73 74]
 [81 82 83]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]
 [30 31 32]
 [39 40 41]
 [48 49 50]
 [57 58 59]
 [66 67 68]
 [75 76 77]
 [84 85 86]]


In [9]:
# 계획
# https://chunml.github.io/ChunML.github.io/project/Creating-Text-Generator-Using-Recurrent-Neural-Network/ 를 참고하여
# input의 각 글자는 알파벳 총 개수 + 1만큼의 길이를 가진 vector로 표현한다.
# 실험적 : vector 마지막 값은 시작으로부터의 길이값을 나타낸다. 길이 정보를 넣어주었을때 어느정도 선에서
#          시를 끊을 지 학습 할 수 있을 것이라고 생각했기 때문이다.
# 각 vector 원소는 각 알파벳을 나타낸다.
# [0, 0, 0, 0, ... 0] 은 아무것도 아닌 글자를 나타낸다. 즉 아무것도 없는 상태의 시작, 또는 종료, 또는 종료 이후의 글자이다.
gatherer = data_gatherer()

In [10]:
gatherer.clean()

In [11]:
gatherer.gather(['crawler/text1.txt', 'crawler/text2.txt'])